before_install:
  - sudo apt-get update -qq

install:
  - bundle install
  - wget https://polarssl.org/download/polarssl-1.3.9-gpl.tgz 
  - tar -xzvf polarssl-1.3.9-gpl.tgz
  - cd polarssl-1.3.9 && cmake -D USE_SHARED_POLARSSL_LIBRARY:BOOL=ON . && make && sudo make install

language: ruby

rvm:
  - "2.0.0"
  - "1.9.3"

