before_install:
  - sudo apt-get update -qq

install:
  - bundle install
  - curl -O https://tls.mbed.org/download/mbedtls-1.3.10-gpl.tgz
  - tar -xzvf mbedtls-1.3.10-gpl.tgz
  - cd mbedtls-1.3.10 && cmake -D USE_SHARED_MBEDTLS_LIBRARY:BOOL=ON . && make && sudo make install

language: ruby

rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3

notifications:
  slack:
    secure: gnM7a3r5oNA/O/+2NXDB6akdyRlio3RP0v0HCi3+/zOuph03JAWVE8u321vkDYdDUhOzWKA37FH3buUwULKjl3TBGto5DFDHh4BCT7jJyt2cLC2cZzC8Q5NZYDTUwXFlJnbWI81yZuTAG80MSrhQLRi7wZyZjWmWCQXbwIk179I=
