before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpolarssl-dev
language: ruby
rvm:
  - 2.0.0
  - 1.9.3
notifications:
  slack:
    secure: gnM7a3r5oNA/O/+2NXDB6akdyRlio3RP0v0HCi3+/zOuph03JAWVE8u321vkDYdDUhOzWKA37FH3buUwULKjl3TBGto5DFDHh4BCT7jJyt2cLC2cZzC8Q5NZYDTUwXFlJnbWI81yZuTAG80MSrhQLRi7wZyZjWmWCQXbwIk179I=
